/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ModuloUsuario;

import ModuloCliente.GestionClientes;
import System.Conexion;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.font.FontRenderContext;
import java.awt.geom.AffineTransform;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;


public class Login extends javax.swing.JFrame {
Conexion conn = new Conexion();
  
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Textusuario = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Password = new javax.swing.JPasswordField();
        Buttonentrar = new javax.swing.JButton();
        Buttonsalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("APP PELICULAS");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel2.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jLabel2.setText("Usuario:");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel3.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jLabel3.setText("Contraseña:");
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        Buttonentrar.setText("ENTRAR");
        Buttonentrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonentrarActionPerformed(evt);
            }
        });

        Buttonsalir.setText("SALIR");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(185, 185, 185))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(Password))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(41, 41, 41)
                                .addComponent(Textusuario, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(Buttonentrar)
                        .addGap(46, 46, 46)
                        .addComponent(Buttonsalir)))
                .addContainerGap(163, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(Textusuario, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(Password, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Buttonentrar)
                    .addComponent(Buttonsalir))
                .addContainerGap(73, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonentrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonentrarActionPerformed
        String user=Textusuario.getText();
        String pass=Password.getText();
        double i= 1.4;
        int j = 0;
        int result = conn.validaUser(user, pass);
        if(result == 0){
            JOptionPane.showMessageDialog(this,"Error en credenciales", "Error de Login",JOptionPane.INFORMATION_MESSAGE);
        }else{
            Menu m =new Menu();
            this.dispose();// ocultar ventana activa, en otras palabras a la clase LOGIN
            m.show();// mostrar ventana del menu
            try{
                ResultSet rs1= conn.queryResult("SELECT r.nomrol as rol, p.nompriv as privilegio, p.modulo FROM privilegios p INNER JOIN roles r on r.idrol= "+result+" AND r.estadorol='A' INNER JOIN roles_has_privilegios rp ON rp.idrol=r.idrol AND rp.idpriv=p.idpriv AND rp.estado='A' WHERE p.estadopriv ='A';");
                while(rs1.next()){ //Cargar todos los privilegios del rol autenticado.
                    String modulo = rs1.getString("modulo");
                    String privilegio = rs1.getString("privilegio");//Cargo el nombre del privilegio
                    /* Transforma la fuente rendizada y lo convierte a graficos */
                    AffineTransform affinetransform = new AffineTransform();
                    /* Cargar el contexto de la fuente a renderizar */
                    FontRenderContext frc = new FontRenderContext(affinetransform,true,true);
                    /* Creamos el boton con el texto del privilegio*/
                    jButton1 = new javax.swing.JButton(); //definir un boton
                    Font font = new java.awt.Font("Segoe UI", 0, 18); //definimos una fuente de texto
                    jButton1.setFont(font); // asigno la fuente al boton
                    jButton1.setText(privilegio); //asigno texto
                    //Ubicar el boton en la ventana setBounds(posicion x horz, posicion y vert,ancho,alto) del boton
                    jButton1.setBounds(52, 132+j, (int)(font.getStringBounds(privilegio, frc).getWidth()* i) , 50); // Posicion x,y,ancho y alto
                    jButton1.addActionListener(new ActionListener(){
                        public void actionPerformed(ActionEvent e){
                            m.dispose(); //eliminar la ventana de menu
                            switch(modulo){
                                case "Gestion Clientes": GestionClientes cli = new GestionClientes(); cli.show(); break;
                                //case "gestion de pedidos 2": GestionClientes cli2 = new GestionClientes(); cli2.show();break;
                            }
                        }
                    });
                    m.add(jButton1);// Añado el boton a mi menu

                    j+=100;
                }
            }catch(SQLException e){

            }
        }
    }//GEN-LAST:event_ButtonentrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }
private javax.swing.JButton jButton1;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Buttonentrar;
    private javax.swing.JButton Buttonsalir;
    private javax.swing.JPasswordField Password;
    private javax.swing.JTextField Textusuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
